## Declaring Tensors

In [1]:
# 1.Fixd tensors

import tensorflow as tf
# A zero filled tensor with dim [10,20]
zero_tsr = tf.zeros([10,20])
# A one filled tensor with dim [10,20]
one_tsr = tf.ones([10,20])
# A constant(42 here) filled tensor with dim [10,20,30]
filled_tsr = tf.fill([10,20,30], 42)
# A tensor from an existing constant
constant_tsr = tf.constant([1,2,3])

# 2.Tensors of similar shape
zeros_similar = tf.zeros_like(constant_tsr)
ones_similar = tf.ones_like(constant_tsr)
# Note: constant_tsr should be initialized first

# 3.Sequence tensors
linear_tsr = tf.linspace(start = 0., stop = 1., num = 3)
# [0.0, 0.5, 1.0]
integer_seq_tsr = tf.range(start = 6, limit = 15, delta = 3)
# [6, 9, 12]

# 4.Random tensors
# Random numbers from a uniform distribution with dim [2,4]
randunif_tsr = tf.random_uniform([2,4], minval = 0, maxval = 1)
# minval but not maxval (minval<=x<maxval)
# Random numbers from a normal distribution with dim [2,4]
randnorm_tsr = tf.random_normal([2,4], mean=0., stddev = 1.)
# Random numbers from a normal distribution with dim [2,4] and bounds(2 standard deviations)
runcnorm_tsr = tf.truncated_normal([2,4], mean = 0., stddev = 1.)
# Shuffle an array
shuffled = tf.random_shuffle(randnorm_tsr)
# cropped = tf.random_crop()

# After create tensors, the corresponding variables may
# also be created by wrapping the tensor in th Variable()
# function
my_var = tf.Variable(tf.zeros([1,2]))

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


## Using Placeholders and Variables

In [4]:
sess = tf.Session()
import numpy as np
x_vals = np.array([1,2,3,5,6])
x_data = tf.placeholder(tf.float32)
const = tf.constant(4.)
product = tf.multiply(const, x_data)
for x_val in x_vals:
    print(sess.run(x_data, feed_dict={x_data:x_vals}))

[ 1.  2.  3.  5.  6.]
[ 1.  2.  3.  5.  6.]
[ 1.  2.  3.  5.  6.]
[ 1.  2.  3.  5.  6.]
[ 1.  2.  3.  5.  6.]
